app:
  name: api-kamarhitung
  port: ":4000"
  code: "kmht"
  encryption: 
    salt: 10
    jwt_secret: iniAdalahSecretToken
    
db: 
  host: localhost
  port: 5432 
  name: postgres
  user: postgres
  password: password
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60 #second